# 共通で設定する環境変数
[env]
GLOBAL = "global env"

# extendでタスクごとに追加できる環境変数
[tasks.set-env-local.env]
LOCAL = "local env"

[tasks.run]
# extendがないとパニックする
extend = "set-env-local"
command = "cargo"
args = ["run"]